#Dica apagando uma letra clicando Ctrl+espaço ajusta o formato do properties para yml

#logging:
#  level:
#    org.springframework.web: DEBUG
    
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
